# Numpy

## Array Oluşturmak

In [5]:
import numpy as np
a = np.array([0,1,2,3])
type(a)

numpy.ndarray

In [6]:
# Tüm elemanlar tek bir sayı tipinde tutulur.
a = np.array([0,1.9,2,3])
a

array([0. , 1.9, 2. , 3. ])

In [8]:
#Eğer tipi belirtmek istersek dtype argümanı kullanılır

a = np.array([0,1.9,2,3],dtype = int)
a

array([0, 1, 2, 3])

## Sıfırdan Array Oluşturmak

In [11]:
#Sıfırlardan oluşan array oluşturulabilir, eleman sayısı parametre olarak verilir. Varsayılan olarak float oluşturulur.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
#Birlerden oluşan array oluşturulabilir, eleman sayısı parametre olarak verilir. Varsayılan olarak float oluşturulur.
#Ayrıca iki parametre verilip matris de oluşturulabilir.
np.ones((4,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
#Eğer sadece istediğimiz sayıdan bi array oluşturmak istersek full kullanılır.
#İlk parametresi array boyutu, ikincisi oluşturulacak sayı
np.full((2,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [17]:
#Doğrusal dizi oluşturmak için arange fonksiyonu kullanılır. 
#İlk parametre başlangıç sayısı, ikincisi bitiş sayısı(dahil değil) , üçüncüsü artış miktarı
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
#İki sayı arasında belirli değer oluşturmak için linspace fonksiyonu kullanılır.
#İlk parametre başlangıç, ikincisi bitiş(dahil), üçüncüsü ise kaç adet sayı oluşturulacağı
np.linspace(0,100,7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

In [20]:
#İstatistik dersindeki gibi normal dağılımlara uygun sayılar oluşturmak için random.normal kullanılır.
#İlk parametresi dağılımın ortalaması, ikincisi standart sapması, üçüncüsü ise array boyutu
np.random.normal(4,0.17,(3,2))

array([[3.828481  , 4.12152738],
       [4.05893843, 4.1810084 ],
       [4.21611741, 3.95650794]])

In [21]:
#int değerlerden rastgele sayılar oluşturmak için random.randint kullanılır
#İlk parametre başlangıç sayısı, ikincisi bitiş sayısı(dahil değil) , üçüncüsü array boyutu
np.random.randint(0,10,(1,2))

array([[8, 4]])

## Array Özellikleri

* ndim = boyut sayısı
* shape = boyu bilgisi
* size = toplam eleman sayısı
* dtype = hangi tip veri olduğu

In [22]:
a = np.random.randint(0,10,(3,5))
a

array([[3, 2, 0, 0, 0],
       [0, 1, 7, 9, 1],
       [6, 4, 7, 1, 9]])

In [24]:
a.ndim

2

In [25]:
a.shape

(3, 5)

In [26]:
a.size

15

In [27]:
a.dtype

dtype('int32')

## Reshaping İşlemleri

In [35]:
#Bir vektörün tek boyuttan çok boyuta ya da tam tersi dönüşüm gerekebilir. Bu yüzden reshape fonksiyonu kullanılır.
a = np.random.randint(0,10,6)
a

array([4, 7, 2, 7, 4, 9])

In [36]:
a.reshape(3,2)

array([[4, 7],
       [2, 7],
       [4, 9]])

In [38]:
#Vektörün yapısının bozulmadan matris yapılması
a = np.arange(5,10)
a.ndim

1

In [40]:
a = a.reshape((1,5))
a

array([[5, 6, 7, 8, 9]])

In [41]:
a.ndim

2

## Concatenation (Birleştirme)

In [4]:
# Tek boyutta birleştirme
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [6]:
# İki boyutta birleştirme (default axis = 0, yani satır olarak birleştirir)
x = np.array([[1,2,3],[4,5,6]])
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
# Sütün olarak birleştirmek istersek axis = 1 argümanını veriririz.
x = np.array([[1,2,3],[4,5,6]])
np.concatenate([x,x],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Splitting (Ayırma)

_Vektörde Parçalama_

In [13]:
# Vektörü parçalamak için split metodu kullanılır.
# İlk parametreye vektörün ismi, ikinci parametreye [] içerisinde kaçıncı index'e kadar bölüneceği yazılır. n kadar index yazılırsa n+1 vektör oluşur.
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9])
a,b,c = np.split(x,[3,5]) # 3. indexe kadar bir parça, 3ten 5. indexe kadar bir parça, 5.indexten sonuna kadar bir parça
a

array([1, 2, 3])

In [14]:
b

array([4, 5])

In [15]:
c

array([6, 7, 8, 9])

Matriste Parçalama

In [17]:
m = np.arange(16).reshape([4,4])
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
# İki farklı metot vardır. vsplit (Vertical Split) ve hsplit (Horizontal Split)
ust, alt = np.vsplit(m,[2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
sol,sag = np.hsplit(m,[2])
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [24]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sorting

In [30]:
# Vektörde sıralama
import numpy as np
x = np.random.randint(0,100,10)
x

array([40,  7, 56, 89,  1, 38, 65, 93,  7, 17])

In [31]:
np.sort(x)

array([ 1,  7,  7, 17, 38, 40, 56, 65, 89, 93])

In [35]:
# Matriste sıralama
y = np.random.normal(20,5,(3,3))
y

array([[ 9.00570408, 18.11202894, 20.75375553],
       [28.74245988, 22.03478231, 19.63117713],
       [ 9.8102129 , 21.52317728, 16.74768433]])

In [36]:
np.sort(y,axis = 1)  # axis = 1 argümanıyla her satır kendi içinde sıralanır.

array([[ 9.00570408, 18.11202894, 20.75375553],
       [19.63117713, 22.03478231, 28.74245988],
       [ 9.8102129 , 16.74768433, 21.52317728]])

In [37]:
np.sort(y,axis = 0)  # axis = 1 argümanıyla her sütün kendi içinde sıralanır.

array([[ 9.00570408, 18.11202894, 16.74768433],
       [ 9.8102129 , 21.52317728, 19.63117713],
       [28.74245988, 22.03478231, 20.75375553]])

## Alt Küme Üzerinde İşlemler

In [38]:
# Normal eşitleme yapıldığında RAM üzerindeki adresi atar bu yüzden alt küme aslında üst kümedeki elemanları gösterir.
# Bağımsız olarak atamak için kopyalanacak vektörün sonuna copy() metodu uygulanır.

a = np.random.randint(10, size = (5,5))
a

array([[1, 3, 7, 3, 2],
       [9, 9, 2, 9, 1],
       [4, 9, 6, 7, 9],
       [2, 8, 0, 6, 8],
       [7, 3, 1, 1, 9]])

In [40]:
b = a[0:2,3:5]
b

array([[3, 2],
       [9, 1]])

In [41]:
b[0,0] = 777777
b

array([[777777,      2],
       [     9,      1]])

In [42]:
a

array([[     1,      3,      7, 777777,      2],
       [     9,      9,      2,      9,      1],
       [     4,      9,      6,      7,      9],
       [     2,      8,      0,      6,      8],
       [     7,      3,      1,      1,      9]])

In [43]:
#Şimdi copy kullanalım
x = np.random.randint(10, size = (3,3))
x

array([[5, 1, 9],
       [6, 5, 2],
       [7, 6, 8]])

In [46]:
y = x[:,1:3].copy()
y

array([[1, 9],
       [5, 2],
       [6, 8]])

## Fancy ve Slice Indexleme

In [47]:
# Fancy Indexleme bir vektöre ya da matrise vektör şeklinde indexlerin verilmesine denir.
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
a[1,[1,2]] # [1,2] işleminin yapılması Fancy Indexing olarak geçer

array([4, 5])

In [52]:
# Slice Indexing de : ifadesinin kullanıldığı indexlemelerdir.

## Koşullu İşlemler

In [53]:
# Fancy Index ile karşılaştırma işlemleri gerçeklşetirilebilir.
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
v[v < 5] # v<5 ifadesi fancy ile çalışır.

array([0, 1, 2, 3, 4])

## Matematiksel İşlemler

In [58]:
v * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
v % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

Numpy Arrayinde bu işlemlerin yapılması ufunc sayesinde oluyor. 
Arkaplanda np.multiply(v,2) koduyla çarpma işlemi gerçekleştiriliyor.

## İki Bilinmeyenli Denklem Çözümü

Numpy, matematiğin lineer cebir kısmına yönelik bir kütüphanedir. Lineer cebir çözümü için linalg adlı bir modülü vardır.

In [ ]:
#Problem :    5*x0 + 4*x1 = 158          x0-3*x1 = 1           x0,x1 = ?

In [69]:
a = np.array([[5,4],[1,3]])
b = np.array([158,5])
a

array([[5, 4],
       [1, 3]])

In [70]:
b

array([158,   5])

In [71]:
np.linalg.solve(a,b)

array([ 41.27272727, -12.09090909])