# **Numpy**

## Array Oluşturmak

In [1]:
import numpy as np
a = np.array([0,1,2,3])
type(a)

numpy.ndarray

Tüm elemanlar tek bir sayı tipinde tutulur.

In [2]:
a = np.array([0,1.9,2,3])
a

array([0. , 1.9, 2. , 3. ])

Eğer tipi belirtmek istersek dtype argümanı kullanılır

In [3]:
a = np.array([0,1.9,2,3],dtype = int)
a

array([0, 1, 2, 3])

## Sıfırdan Array Oluşturmak

Sıfırlardan oluşan array oluşturulabilir, eleman sayısı parametre olarak verilir. Varsayılan olarak float oluşturulur.

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Birlerden oluşan array oluşturulabilir, eleman sayısı parametre olarak verilir. Varsayılan olarak float oluşturulur. Ayrıca iki parametre verilip matris de oluşturulabilir.

In [5]:
np.ones((4,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Eğer sadece istediğimiz sayıdan bi array oluşturmak istersek full kullanılır. İlk parametresi array boyutu, ikinci parametresi ise oluşturulacak sayı olacaktir.

In [6]:
np.full((2,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

Doğrusal dizi oluşturmak için arange fonksiyonu kullanılır.  İlk parametre başlangıç sayısı, ikincisi bitiş sayısı(dahil değil) , üçüncüsü artış miktarı

In [7]:
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

İki sayı arasında belirli değer oluşturmak için linspace fonksiyonu kullanılır. İlk parametre başlangıç, ikincisi bitiş(dahil), üçüncüsü ise kaç adet sayı oluşturulacağı

In [8]:
np.linspace(0,100,7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

İstatistik dersindeki gibi normal dağılımlara uygun sayılar oluşturmak için random.normal kullanılır. İlk parametresi dağılımın ortalaması, ikincisi standart sapması, üçüncüsü ise array boyutu

In [9]:
np.random.normal(4,0.17,(3,2))

array([[4.05588273, 3.91699368],
       [4.01488021, 3.98663694],
       [4.06992435, 4.0669133 ]])

int değerlerden rastgele sayılar oluşturmak için random.randint kullanılır. İlk parametre başlangıç sayısı, ikincisi bitiş sayısı(dahil değil) , üçüncüsü array boyutu

In [10]:
np.random.randint(0,10,(1,2))

array([[3, 7]])

## Array Özellikleri

* ndim = boyut sayısı
* shape = boyu bilgisi
* size = toplam eleman sayısı
* dtype = hangi tip veri olduğu

In [11]:
a = np.random.randint(0,10,(3,5))
a

array([[1, 4, 3, 2, 4],
       [6, 6, 8, 3, 7],
       [5, 5, 3, 0, 2]])

In [12]:
a.ndim

2

In [13]:
a.shape

(3, 5)

In [14]:
a.size

15

In [15]:
a.dtype

dtype('int64')

## Reshaping İşlemleri

Bir vektörün tek boyuttan çok boyuta ya da tam tersi dönüşüm gerekebilir. Bu yüzden reshape fonksiyonu kullanılır.

In [16]:
a = np.random.randint(0,10,6)
a

array([2, 8, 3, 6, 0, 9])

In [17]:
a.reshape(3,2)

array([[2, 8],
       [3, 6],
       [0, 9]])

Vektörün yapısının bozulmadan matris yapılması

In [18]:
a = np.arange(5,10)
a.ndim

1

In [19]:
a = a.reshape((1,5))
a

array([[5, 6, 7, 8, 9]])

In [20]:
a.ndim

2

## Concatenation (Birleştirme)

Tek boyutta birleştirme

In [21]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

İki boyutta birleştirme (default axis = 0, yani satır olarak birleştirir)

In [22]:
x = np.array([[1,2,3],[4,5,6]])
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Sütün olarak birleştirmek istersek axis = 1 argümanını veriririz.

In [23]:
x = np.array([[1,2,3],[4,5,6]])
np.concatenate([x,x],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Splitting (Ayırma)

Vektörü parçalamak için split metodu kullanılır. İlk parametreye vektörün ismi, ikinci parametreye [] içerisinde kaçıncı index'e kadar bölüneceği yazılır. n kadar index yazılırsa n+1 vektör oluşur.

In [24]:
x = np.array([1,2,3,4,5,6,7,8,9])
a,b,c = np.split(x,[3,5]) # 3. indexe kadar bir parça, 3ten 5. indexe kadar bir parça, 5.indexten sonuna kadar bir parça
a

array([1, 2, 3])

In [25]:
b

array([4, 5])

In [26]:
c

array([6, 7, 8, 9])

Matriste Parçalama

In [27]:
m = np.arange(16).reshape([4,4])
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

İki farklı metot vardır. vsplit (Vertical Split) ve hsplit (Horizontal Split)

In [28]:
ust, alt = np.vsplit(m,[2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
sol,sag = np.hsplit(m,[2])
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [31]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sorting

Vektorde Siralama

In [32]:
x = np.random.randint(0,100,10)
x

array([12, 71, 59, 44, 98, 86, 90, 26,  3, 94])

In [33]:
np.sort(x)

array([ 3, 12, 26, 44, 59, 71, 86, 90, 94, 98])

Matriste Sıralama

In [34]:
y = np.random.normal(20,5,(3,3))
y

array([[15.01729969, 23.88968626, 18.60386573],
       [26.96702607, 24.81871679, 15.09032485],
       [13.83829509, 12.506954  , 20.70777706]])

axis = 1 argümanıyla her satır kendi içinde sıralanır.

In [35]:
np.sort(y,axis = 1)

array([[15.01729969, 18.60386573, 23.88968626],
       [15.09032485, 24.81871679, 26.96702607],
       [12.506954  , 13.83829509, 20.70777706]])

axis = 0 argümanıyla her sütün kendi içinde sıralanır.

In [36]:
np.sort(y,axis = 0)

array([[13.83829509, 12.506954  , 15.09032485],
       [15.01729969, 23.88968626, 18.60386573],
       [26.96702607, 24.81871679, 20.70777706]])

## Alt Küme Üzerinde İşlemler

Normal eşitleme yapıldığında RAM üzerindeki adresi atar bu yüzden alt küme aslında üst kümedeki elemanları gösterir. Bağımsız olarak atamak için kopyalanacak vektörün sonuna copy() metodu uygulanır.

In [37]:
a = np.random.randint(10, size = (5,5))
a

array([[0, 6, 3, 1, 8],
       [7, 0, 3, 8, 9],
       [2, 3, 7, 0, 0],
       [7, 8, 8, 6, 4],
       [7, 4, 1, 1, 4]])

In [38]:
b = a[0:2,3:5]
b

array([[1, 8],
       [8, 9]])

In [39]:
b[0,0] = 777777
b

array([[777777,      8],
       [     8,      9]])

In [40]:
a

array([[     0,      6,      3, 777777,      8],
       [     7,      0,      3,      8,      9],
       [     2,      3,      7,      0,      0],
       [     7,      8,      8,      6,      4],
       [     7,      4,      1,      1,      4]])

Şimdi copy kullanalım

In [41]:
x = np.random.randint(10, size = (3,3))
x

array([[4, 0, 7],
       [6, 5, 8],
       [6, 0, 7]])

In [42]:
y = x[:,1:3].copy()
y

array([[0, 7],
       [5, 8],
       [0, 7]])

## Fancy ve Slice Indexleme

Fancy Indexleme bir vektöre ya da matrise vektör şeklinde indexlerin verilmesine denir.

In [43]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

[1,2] işleminin yapılması Fancy Indexing olarak geçer

In [44]:
a[1,[1,2]]

array([4, 5])

Slice Indexing de _:_ operatorunun kullanıldığı indexlemelerdir.

## Koşullu İşlemler

Fancy Index ile karşılaştırma işlemleri gerçeklşetirilebilir.

In [45]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

v<5 ifadesi fancy ile çalışır.

In [46]:
v[v < 5]

array([0, 1, 2, 3, 4])

## Matematiksel İşlemler

In [47]:
v * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
v % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

Numpy Arrayinde bu işlemlerin yapılması ufunc sayesinde oluyor. 
Arkaplanda np.multiply(v,2) koduyla çarpma işlemi gerçekleştiriliyor.

## İki Bilinmeyenli Denklem Çözümü

Numpy, matematiğin lineer cebir kısmına yönelik bir kütüphanedir. Lineer cebir çözümü için linalg adlı bir modülü vardır.

Problem :    
* $5x_0 + 4x_1 = 158$
* $x_0-3x_1 = 1$           
* $x_0,x_1 = ?$

In [49]:
a = np.array([[5,4],[1,3]])
b = np.array([158,5])
a

array([[5, 4],
       [1, 3]])

In [50]:
b

array([158,   5])

In [51]:
np.linalg.solve(a,b)

array([ 41.27272727, -12.09090909])